
#server.port=9999
#spring.datasource.url=jdbc:postgresql://localhost:5432/blog
#spring.datasource.username=postgresql
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
# server.address=192.168.21.198
spring.jpa.hibernate.ddl-auto=update
server.port=9999
#spring.jpa.show-sql=true

#otel.traces.exporter=jaeger
#otel.exporter.jaeger.endpoint=http://localhost:14250
#tracing.url=http://localhost:4318/v1/trace

#managemenr.tracing.sampling.probability=1.0

logging.pattern.level=%.-5level [${spring.application.name},%X{traceId:-},%X{spanId:-}]
otel.propagators=tracecontext,b3
otel.resource.attributes=environment=dev,xyz=foo
